- name: check the number 
  hosts: localhost
  vars_prompt: 
  - name: number
    prompt: check the number
    private: no
  tasks:
  - name: number is less than 40
    ansible.builtin.debug:
      msg: "given number {{number}} is less than 40"
    when: number | int < 40

  - name: number is greater than or equal to 
    ansible.builtin.debug:
      msg: "given number {{number}} is greater than or equal to 40"
    when: number | int >= 40 