- name: data type 
  hosts: localhost
  vars:
   course: "Devops with aws"
   Tools:
   - Linux
   - shell scripting
   - ansible
   - terraform
   experience: 
    devops: 3
    aws: 3
    linux: 2
   realproject: true
  tasks:
  - name: print data type
    ansible.builtin.debug:
      msg: "course: {{course}}, Tools will cover: {{Tools}}, Experience is:{{experience}}, is realtime project experience: {{realproject}}" 
