- name: change to lower case
  hosts: localhost
  vars:
   greeting: "GOOD MORNING"
  tasks:
  - name : lowercase
    ansible.builtin.debug:
      msg: "{{ greeting  | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
   numbers: [2, 4, 5, 5, 6, 2, 8]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"    

- name: min and max 
  hosts: localhost
  vars:
   ages: [12, 7, 27, 35, 57]
  tasks:
  - name: min and max
    ansible.builtin.debug:
      msg: " min age is :{{ ages | min }} max age is : {{ ages| max }}"          