- name: install applications
  hosts: localhost
  become: yes 
  connection: ssh
  tasks:
  - name: install package
    ansible.builtin.yum:
     name: {{ item }}
     state: latest
    loop:
    - nginx
    - mysql
     

