- name: install applications
  hosts: localhost
  become: yes 
  tasks:
  - name: install applications
    ansible.builtin.debug:
    yum:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
   