- name: install ngix
  hosts: dev
  become: yes # to access root 
  tasks:
  - name: install nginx
     ansible.builtin.dnf:
      name: install
      state: latest 

  - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes  

