- name: variables
  hosts: localhost
  vars: 
   course: "Ansible"
   trainer: "Venkat"
   duration: "25hrs"
  tasks:
   - name: print information
     ansible.builtin.debug:
       msg: "I am learning {{course}} from trainer {{trainer}}, duration is {{duration}}"