- name: variables
  hosts: localhost
  vars: 
   course: "JAVA"
   trainer: "BARATH"
   duration: "100hrs"
  tasks:
   - name: print information
     ansible.builtin.debug:
       msg: "I am learning {{course}} from trainer {{trainer}}, duration is {{duration}}"