- name: print varaibles
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false
  - name: PASSWORD 
    prompt: please enter your password
    private: true 
  tasks:
  - name: print vasriables
    ansible.builtin.debug:
      msg: "Hi, username: {{USERNAME}. password is : {{PASSWORD}}"    
